import type { Metadata } from "next";



import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";
import { Navigation } from "./components/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={`antialiased max-w-[1480px] mx-auto px-[124px]`}
      >
        <header>
          <Navigation/>
        </header>
        {children}
      </body>
    </html>
  );
}
